### PR TITLE
v1.4 rebased

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)

Rebase of #3

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@seanyen 
This is ready to merge.

**Comment by wolfv** [comment]
awesome!

**Comment by seanyen** [comment]
LGTM. Merging.

**Comment by seanyen** [comment]
@Tobias-Fischer I saw some good portable improvement in the patches. Are you able to drive those changes to the upstream? 😉

**Comment by Tobias-Fischer** [comment]
They are all taken from upstream PRs :)

**Pull request merged**
