### PR TITLE
First steps toward unix build

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

It doesn't build locally, it fails saying that the lib cannot be found - I have no clue why. Maybe @wolfv @seanyen you would know?

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
Hi @seanyen,
This PR only fails on Windows - I am assuming because it's not compatible with vs2017 (see #2). Do you have any idea why?

/cc @wolfv

**Comment by seanyen** [comment]
Can you try to pin `sip` to `4.19.20`? I found there is some hard-coded prefix is no longer patched by newer `conda-build`. I am suspecting it is to do with https://github.com/conda/conda-build/issues/3909#issuecomment-626586540.

**Comment by Tobias-Fischer** [comment]
I should have read this comment earlier - it was indeed the sip version!

**Comment by seanyen** [comment]
LGTM.

**Pull request merged**
