### PR TITLE
Bump to v1.5.1 with fixes

### PR DESCRIPTION
**Pull request by traversaro**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
Removed several patches that have been upstreamed: 

* https://github.com/orocos/orocos_kinematics_dynamics/pull/334
* https://github.com/orocos/orocos_kinematics_dynamics/pull/335
* https://github.com/orocos/orocos_kinematics_dynamics/pull/336
* https://github.com/orocos/orocos_kinematics_dynamics/pull/337

**Review by Tobias-Fischer — APPROVED** [review]

**Comment by Tobias-Fischer** [comment]
Happy to merge this in if you think it's ready @traversaro

**Comment by Tobias-Fischer** [comment]
Fix #14

**Comment by traversaro** [comment]
> Happy to merge this in if you think it's ready @traversaro 

It is ready!

**Pull request merged**
